# lex-robot/examples/skill_fridge_report_demo.lex — "go to the fridge and
# show me what's inside, with a picture" — the display-app design from the
# README/screen conversation, built and run for real.
#
# Three pieces, each already discussed as a separate decision:
#   1. NAVIGATION — a hardcoded fridge coordinate, same as every other demo
#      in this repo. Learning the geometry of a home by visiting it (SLAM)
#      is explicitly out of scope here — see docs/XLEROBOT_SETUP.md's
#      "Base drifts off target" note and the README's mapping discussion.
#   2. PERCEPTION → JUDGMENT split — `list_visible_items` (src/skills.lex)
#      is deliberately [net] only, not [net, sense]: interpreting an
#      already-captured photo is judgment on data in hand, not a new
#      physical sense read. It calls examples/skills_api_stub.py's
#      `/vision/describe`, a stand-in for a real multimodal vision API.
#   3. DISPLAY — `show_report` (src/skills.lex), the composite DisplayState
#      kind added alongside image/video/url/text specifically for this:
#      a picture AND a findings list, shown together.
#
# Tier-1's read_camera stub is an HONEST simulation (see
# xlerobot_sidecar.py: "no real encoder/camera... empty" — same convention
# as speak's "(simulated, no speaker)"), so it returns no real bytes. This
# demo doesn't fake that — it uses a small bundled placeholder photo
# (examples/fridge_photo.png, generated by examples/gen_fridge_photo.py, a
# few colored blocks standing in for items) as the thing that got
# "captured," exactly the same honesty convention locate_object's
# CANNED_OBJECT_WORLD already uses for vision it doesn't really have.
#
# Run: examples/skill_fridge_report_demo_run.sh (starts the XLeRobot stub
# sidecar + the skills API stub, runs this, tears both down).

import "std.env" as env

import "std.io" as io

import "std.str" as str

import "../src/types" as t

import "../src/skills" as skills

# examples/fridge_photo.png, base64-encoded (see examples/gen_fridge_photo.py).
# A real deployment would base64-encode whatever read_camera just captured;
# this is that same representation of the same bundled placeholder image
# show_report also points the kiosk display at by file path below.
fn fridge_photo_b64() -> Str {
  "iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAAB/UlEQVR42u3bqw2AQBBAQWpCoymCSqgETTlrMBSBISEYPAKLguMTmMurYDPZVZeN8yQlLzMCgSWwBJYElsASWBJYAktgSWAJLIElgSWwBJYElsASWBJYAktgSWAJLIElgSWwBJYElsASWBJYAktgSWB9s+WuBxZYYAksgQUWWGDtNQz1RYEFFlhggQUWWGCBBRZYYIEFFlhggQUWWGCBBRZYYIEFFlhggQUWWGCBBRZYZ+qL/KLAAgsssMACCyywwAILLLDAAgsssMACCyywwAILLLDAAgsssMACCyywwAILLLDAAgsssMACCyywwAILLLDAAgsssMACCyywwJLAElgCSwJLN8OKLqTk2VhyCgWWwDIFgSWwBJYElsASWBJYAktgSWDpt7Cqtnx/BIAFFlhggQWWwAILrP/BiqZ4JLDAAgsssMACCyywwAILLLDAAgsssMACCyywwAILLLDAAgsssMACCyywfKYQWAJLAktgCSwJLIElsCSwBJbAksASWAJLAktgCSwJLIElsCSwBJbAksASWAJLAktgCSwJLIElsKQNVnQhJc/GklMosASWKQgsgSWwJLAElsCSwBJYAksCS2AJLAksgSWwJLAElsCSwBJYAksCS2AJLAksgSWwJLAElsCSjrQCkGTXt7xkQygAAAAASUVORK5CYII="
}

fn robot(sidecar_url :: Str) -> t.Robot {
  { sidecar_url: sidecar_url, grant: { skills: ["move_base", "show_report"], ws_min: { x: 0.0, y: 0.0, z: 0.0 }, ws_max: { x: 5.0, y: 5.0, z: 1.0 }, max_velocity: 1.0, max_force: 10.0, max_grip_force: 10.0, budget_actions: 10, budget_wall_ms: 60000 } }
}

fn fridge_location() -> t.Vec3 {
  { x: 3.5, y: 1.0, z: 0.0 }
}

fn items_to_lines(items :: List[Str]) -> Str {
  str.join(items, ", ")
}

fn run() -> [env, net, sense, actuate, io] Unit {
  let sidecar_url := match env.get("XLE_SIDECAR_URL") {
    None => "http://localhost:8900",
    Some(u) => u,
  }
  let vision_url := match env.get("VISION_STUB_URL") {
    None => "http://localhost:8930",
    Some(u) => u,
  }
  let r := robot(sidecar_url)
  let __0 := io.print("══════════════════════════════════════════════════════")
  let __1 := io.print("   FRIDGE REPORT  ·  go look, then show me what you found")
  let __2 := io.print("══════════════════════════════════════════════════════")
  let __3 := io.print("")
  let __4 := io.print("── 1. navigate (hardcoded coordinate — SLAM is out of scope, see module comment) ──")
  let move_outcome := skills.move_base(r, fridge_location(), 0.3)
  let __5 := io.print(match move_outcome {
    Reached => "  reached the fridge",
    Stalled(m) => str.concat("  stalled: ", m),
    Denied(m) => str.concat("  denied: ", m),
    Killed(m) => str.concat("  killed: ", m),
    Timeout => "  timeout",
  })
  let __6 := io.print("")
  let __7 := io.print("── 2. perceive -> judge (list_visible_items, [net] only, no new [sense]) ──")
  let items := match skills.list_visible_items(vision_url, fridge_photo_b64()) {
    Err(e) => {
      let __p := io.print(str.concat("  vision call failed: ", e))
      []
    },
    Ok(xs) => {
      let __p := io.print(str.concat("  found: ", items_to_lines(xs)))
      xs
    },
  }
  let __8 := io.print("")
  let __9 := io.print("── 3. display (show_report: picture + list, together) ──")
  let report_outcome := skills.show_report(r, "examples/fridge_photo.png", items, "fridge contents, just now")
  let __10 := io.print(match report_outcome {
    Reached => "  report shown on the kiosk display",
    Stalled(m) => str.concat("  stalled: ", m),
    Denied(m) => str.concat("  denied: ", m),
    Killed(m) => str.concat("  killed: ", m),
    Timeout => "  timeout",
  })
  io.print("")
}

